name: Check Menu Update

on:
  schedule:
    - cron: "0 7 * * 1"   # Every Monday at 7 AM
    - cron: "0 8 * * 1"  # Every Monday at 8 AM
    - cron: "0 9 * * 1"  # Every Monday at 9 AM
    - cron: "0 12 * * 1"  # Every Monday at 12 noon
    - cron: "0 8 * * 2"  # Tuesday at 8 AM, edgecase if Monday is a bank holiday
  workflow_dispatch:

jobs:
  check_menu:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run script
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: |
        python check_menu.py

    - name: Calculate Monday's Date
      id: get_monday
      run: |
        python -c "import datetime; today = datetime.date.today(); weekday = today.weekday(); monday = today - datetime.timedelta(days=weekday); print(f'MONDAY_DATE={monday.strftime('%d %b %Y')}')" >> $GITHUB_ENV

    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add weekly_menu.jpg
        if git diff --cached --quiet; then
          echo "No changes to commit."
          exit 0
        fi
        git commit -m "📜Update weekly menu for week starting ${{ env.MONDAY_DATE }} 😋"

    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
